name: Salesforce CI Pipeline

on:
  pull_request:
    branches:
      - release  # This triggers the action when a PR is opened against the release branch

jobs:
  validate-deploy:
    name: Validate Deployment to SIT (PR Check)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: |
          curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt install -y nodejs
          npm install -g @salesforce/cli

      - name: Install CumulusCI
        run: |
          pip install cumulusci

      - name: Debugging SF_USERNAME_SIT
        run: echo "SF_USERNAME_SIT: ${{ secrets.SF_USERNAME_SIT }}"

      - name: Set environment variables for SF login
        env:
          SF_CONSUMER_KEY_SIT: ${{ secrets.SF_CONSUMER_KEY_SIT }}
          SF_JWT_KEY_SIT: ${{ secrets.SF_JWT_KEY_SIT }}
          SF_USERNAME_SIT: ${{ secrets.SF_USERNAME_SIT }}

      - name: Authenticate with Salesforce Org (SIT)
        run: |
          sf org login jwt --client-id $SF_CONSUMER_KEY_SIT \
                           --jwt-key-file $SF_JWT_KEY_SIT \
                           --username $SF_USERNAME_SIT \
                           --instance-url https://grinnell--ccitestsit.sandbox.my.salesforce.com \
                           --set-default --loglevel debug

      - name: Import SIT Org into CumulusCI
        run: |
          cci org import --org sit --default
        env:
          SFDX_AUTH_URL: $(sf org display --json | jq -r .result.sfdxAuthUrl)

      - name: Validate feature branch in SIT (Check Only)
        run: |
          cci flow run deploy --org sit --checkonly
        env:
          CUMULUSCI_KEY: ${{ secrets.CUMULUSCI_KEY }}
        
      - name: Run Tests
        run: |
          cci task run run_tests --org sit
        env:
          CUMULUSCI_KEY: ${{ secrets.CUMULUSCI_KEY }}

      - name: Fail on Error
        if: failure()
        run: exit 1

  deploy-release:
    name: Deploy Release to SIT (After Merge)
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: |
          curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt install -y nodejs
          npm install -g @salesforce/cli

      - name: Install CumulusCI
        run: |
          pip install cumulusci

      - name: Authenticate with Salesforce Org (SIT)
        run: |
          sf org login jwt --client-id $SF_CONSUMER_KEY_SIT \
                           --jwt-key-file $SF_JWT_KEY_SIT \
                           --username $SF_USERNAME_SIT \
                           --instance-url https://grinnell--ccitestsit.sandbox.my.salesforce.com \
                           --set-default --loglevel debug

      - name: Import SIT Org into CumulusCI
        run: |
          cci org import --org sit --default
        env:
          SFDX_AUTH_URL: $(sf org display --json | jq -r .result.sfdxAuthUrl)

      - name: Deploy release branch to SIT
        run: |
          cci flow run deploy --org sit
        env:
          CUMULUSCI_KEY: ${{ secrets.CUMULUSCI_KEY }}

      - name: Run Tests
        run: |
          cci task run run_tests --org sit
        env:
          CUMULUSCI_KEY: ${{ secrets.CUMULUSCI_KEY }}
